# Generated by Django 3.1.8 on 2021-04-06 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('store_name', models.CharField(max_length=255, verbose_name='Store')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='store_image/', verbose_name='Image')),
                ('fav', models.BooleanField(default=False, verbose_name='Fav')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 4, 6, 15, 29, 28, 791722))),
            ],
        ),
    ]
